// modules/todo/internal/domain/errors.go
package domain

import "errors"

var (
	// Validation errors
	ErrInvalidTitle   = errors.New("title must be between 1 and 200 characters")
	ErrInvalidDueDate = errors.New("due date must be in the future")
	ErrInvalidID      = errors.New("invalid todo ID")
	// ErrInvalidPriority and ErrInvalidTaskStatus are generated by go-enum in value_objects_enum.go

	// Business rule errors
	ErrCannotCompleteCancelled = errors.New("cannot complete a cancelled task")
	ErrCannotModifyCompleted   = errors.New("cannot modify a completed task")
	ErrTodoNotFound            = errors.New("todo not found")
	ErrTodoAlreadyExists       = errors.New("todo already exists")

	// State transition errors
	ErrInvalidStatusTransition = errors.New("invalid status transition")
)
