// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/pivaldi/mmw-todo/internal/domain/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventDispatcher creates a new instance of MockEventDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventDispatcher {
	mock := &MockEventDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventDispatcher is an autogenerated mock type for the EventDispatcher type
type MockEventDispatcher struct {
	mock.Mock
}

type MockEventDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventDispatcher) EXPECT() *MockEventDispatcher_Expecter {
	return &MockEventDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) Dispatch(ctx context.Context, events []domain.DomainEvent) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.DomainEvent) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockEventDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.DomainEvent
func (_e *MockEventDispatcher_Expecter) Dispatch(ctx interface{}, events interface{}) *MockEventDispatcher_Dispatch_Call {
	return &MockEventDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, events)}
}

func (_c *MockEventDispatcher_Dispatch_Call) Run(run func(ctx context.Context, events []domain.DomainEvent)) *MockEventDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.DomainEvent
		if args[1] != nil {
			arg1 = args[1].([]domain.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_Dispatch_Call) Return(err error) *MockEventDispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, events []domain.DomainEvent) error) *MockEventDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}
