// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/pivaldi/mmw-todo/internal/application/ports"
	"github.com/pivaldi/mmw-todo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Delete(ctx context.Context, id domain.TodoID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TodoID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTodoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TodoID
//   - userID uuid.UUID
func (_e *MockTodoRepository_Expecter) Delete(ctx any, id any, userID any) *MockTodoRepository_Delete_Call {
	return &MockTodoRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockTodoRepository_Delete_Call) Run(run func(ctx context.Context, id domain.TodoID, userID uuid.UUID)) *MockTodoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TodoID
		if args[1] != nil {
			arg1 = args[1].(domain.TodoID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Delete_Call) Return(err error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.TodoID, userID uuid.UUID) error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) FindAll(ctx context.Context, filters ports.Filters) ([]*domain.Todo, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.Filters) ([]*domain.Todo, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.Filters) []*domain.Todo); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.Filters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTodoRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filters ports.Filters
func (_e *MockTodoRepository_Expecter) FindAll(ctx any, filters any) *MockTodoRepository_FindAll_Call {
	return &MockTodoRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filters)}
}

func (_c *MockTodoRepository_FindAll_Call) Run(run func(ctx context.Context, filters ports.Filters)) *MockTodoRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.Filters
		if args[1] != nil {
			arg1 = args[1].(ports.Filters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_FindAll_Call) Return(todos []*domain.Todo, err error) *MockTodoRepository_FindAll_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodoRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, filters ports.Filters) ([]*domain.Todo, error)) *MockTodoRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) FindByID(ctx context.Context, id domain.TodoID, userID uuid.UUID) (*domain.Todo, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TodoID, uuid.UUID) (*domain.Todo, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TodoID, uuid.UUID) *domain.Todo); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TodoID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTodoRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.TodoID
//   - userID uuid.UUID
func (_e *MockTodoRepository_Expecter) FindByID(ctx any, id any, userID any) *MockTodoRepository_FindByID_Call {
	return &MockTodoRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, userID)}
}

func (_c *MockTodoRepository_FindByID_Call) Run(run func(ctx context.Context, id domain.TodoID, userID uuid.UUID)) *MockTodoRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TodoID
		if args[1] != nil {
			arg1 = args[1].(domain.TodoID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) Return(todo *domain.Todo, err error) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id domain.TodoID, userID uuid.UUID) (*domain.Todo, error)) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Health(ctx context.Context) (any, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (any, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) any); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockTodoRepository_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTodoRepository_Expecter) Health(ctx any) *MockTodoRepository_Health_Call {
	return &MockTodoRepository_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockTodoRepository_Health_Call) Run(run func(ctx context.Context)) *MockTodoRepository_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Health_Call) Return(v any, err error) *MockTodoRepository_Health_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTodoRepository_Health_Call) RunAndReturn(run func(ctx context.Context) (any, error)) *MockTodoRepository_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Save(ctx context.Context, todo *domain.Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTodoRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *domain.Todo
func (_e *MockTodoRepository_Expecter) Save(ctx any, todo any) *MockTodoRepository_Save_Call {
	return &MockTodoRepository_Save_Call{Call: _e.mock.On("Save", ctx, todo)}
}

func (_c *MockTodoRepository_Save_Call) Run(run func(ctx context.Context, todo *domain.Todo)) *MockTodoRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Todo
		if args[1] != nil {
			arg1 = args[1].(*domain.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Save_Call) Return(err error) *MockTodoRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_Save_Call) RunAndReturn(run func(ctx context.Context, todo *domain.Todo) error) *MockTodoRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Update(ctx context.Context, todo *domain.Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTodoRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *domain.Todo
func (_e *MockTodoRepository_Expecter) Update(ctx any, todo any) *MockTodoRepository_Update_Call {
	return &MockTodoRepository_Update_Call{Call: _e.mock.On("Update", ctx, todo)}
}

func (_c *MockTodoRepository_Update_Call) Run(run func(ctx context.Context, todo *domain.Todo)) *MockTodoRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Todo
		if args[1] != nil {
			arg1 = args[1].(*domain.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Update_Call) Return(err error) *MockTodoRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_Update_Call) RunAndReturn(run func(ctx context.Context, todo *domain.Todo) error) *MockTodoRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
